# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 21:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age_group', models.CharField(max_length=10)),
                ('room_requirement', models.ManyToManyField(related_name='allowed_rooms', to='scheduling.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('for_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduling.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age_preferences', models.IntegerField(default=0)),
                (
                'availability', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('specialty', models.ManyToManyField(related_name='specialities', to='scheduling.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2016)),
                ('version', models.CharField(max_length=255)),
                ('schedule', models.TextField()),
            ],
        ),
    ]
