# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 15:34
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scheduling', '0003_auto_20160327_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='availability',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=None),
        ),
    ]
