# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_auto_20160327_1912'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Course',
        ),
    ]
