# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_instructor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='name',
        ),
    ]
