# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_remove_instructor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='age_preferences',
        ),
    ]
