# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_auto_20160428_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='type',
            field=models.CharField(choices=[('HD', 'Half Day'), ('FD', 'Full Day')], default='HD', max_length=8),
        ),
    ]
