# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-03 23:02
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_class_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='availability',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=list, size=None),
        ),
    ]
