# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_auto_20160503_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekHeadingsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week1_title', models.CharField(default='Week 1', max_length=255)),
                ('week2_title', models.CharField(default='Week 2', max_length=255)),
                ('week3_title', models.CharField(default='Week 3', max_length=255)),
                ('week4_title', models.CharField(default='Week 4', max_length=255)),
                ('week5_title', models.CharField(default='Week 5', max_length=255)),
                ('week6_title', models.CharField(default='Week 6', max_length=255)),
                ('week7_title', models.CharField(default='Week 7', max_length=255)),
                ('week8_title', models.CharField(default='Week 8', max_length=255)),
                ('week9_title', models.CharField(default='Week 9', max_length=255)),
                ('week10_title', models.CharField(default='Week 10', max_length=255)),
                ('week11_title', models.CharField(default='Week 11', max_length=255)),
                ('week12_title', models.CharField(default='Week 12', max_length=255)),
            ],
        ),
    ]
